package com.eihabitat.eihabitat_server.mapper;

import com.eihabitat.eihabitat_server.dto.request.UserLikePostReq;
import com.eihabitat.eihabitat_server.dto.request.UserSavePostReq;
import com.eihabitat.eihabitat_server.dto.response.UserLikePostResponse;
import com.eihabitat.eihabitat_server.dto.response.UserSavePostResponse;
import com.eihabitat.eihabitat_server.entity.UserLikePost;
import com.eihabitat.eihabitat_server.entity.UserSavePost;
import org.mapstruct.*;
import org.mapstruct.factory.Mappers;

@Mapper(componentModel = "spring")
public interface UserSavePostMapper {
    @Mapping(target = "id", ignore = true) // Ignore the autogenerated ID
    @Mapping(target = "saveAt", expression = "java(java.time.LocalDateTime.now())") // Set current datetime
    UserSavePost toUserSavePost(UserSavePostReq request);

    @Mapping(target = "saveAt", source = "saveAt") // Map the existing datetime
    UserSavePostResponse toUserSavePostResponse(UserSavePost userSavePost);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    void updateUserSavePostFromDto(UserSavePostReq dto, @MappingTarget UserSavePost entity);
}
