spring.application.name=eihabitat-server

spring.datasource.url=jdbc:mysql://localhost:3306/eihabitat_db
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true

spring.data.mongodb.database=eihabitatlocal_db
spring.data.mongodb.uri=mongodb+srv://tanlenguyen00:DnHTjGeIHFH1WSYU@cluster0.dpc8c.mongodb.net
logging.level.org.springframework.data.mongodb.core=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gintoki2107@gmail.com
spring.mail.password=ptxtouupyggyszer
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.signerKey : "uAmDx6zM2iIaPNA4IZApT5mth+IQGj4Oj81VffHvMqyxcK1kgrCmp7qFmASdau9c"
spring.main.allow-bean-definition-overriding=true

spring.security.oauth2.client.registration.google.client-id=1014471315917-pkpbhhms3gi3tl0o60dancrit7le4out.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri=https://eihabitat.site/api/login/oauth2/code/google
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB