spring.application.name=eihabitat-server

spring.datasource.url=jdbc:mysql://localhost:3306/eihabitat_db
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true


spring.data.mongodb.database=eihabitat_db
spring.data.mongodb.uri=mongodb+srv://tanlenguyen00:DnHTjGeIHFH1WSYU@cluster0.dpc8c.mongodb.net
logging.level.org.springframework.data.mongodb.core=DEBUG

jwt.signerKey : "uAmDx6zM2iIaPNA4IZApT5mth+IQGj4Oj81VffHvMqyxcK1kgrCmp7qFmASdau9c"


